### ISSUE TITLE
city not found

### ISSUE THREAD

**Issue by helicopterjeff** [jvicu2001/Simple-Weather-Overlay#5]
love this script, but it can't seem to find any cities. is there a trick to entering this info?

**Comment by helicopterjeff** [comment]
never mind, apparently it takes several minutes for it to "find" a city and display.

**Comment by jvicu2001** [comment]
That wait to find the city doesn't sound good, but it looks like an OpenWeather's problem.

**Comment by helicopterjeff** [comment]
it is working though. seems just the web preview has issues

> --
> Jeff Williams
> about.me/jeffw
> 
> Get American Made Decals and Window Clings!
> www.jnmvinylstudio.com
>
